name: Deploy Services

on:
  workflow_call:
    inputs:
      target-env:
        required: true
        type: string
  workflow_dispatch:
jobs:
  deploy_api:
    name: Deploy API
    uses: ./.github/workflows/deploy-api.yml
    with:
      target-env: ${{ inputs.target-env }}
    secrets: inherit

  deploy_socket:
    name: Deploy Socket Server
    uses: ./.github/workflows/deploy-socket.yml
    with:
      target-env: ${{ inputs.target-env }}
    secrets: inherit
